<?php
/** @var Coolpay_Payment_Block_Payment_Redirect $this */
/** @var Coolpay_Payment_Model_Payment $payment */
$payment = Mage::getModel('coolpaypayment/payment');

$order = $this->getOrder();
$coolpay_state = Mage::getSingleton('core/session')->getCoolpayState();

// Get array of selections
if (isset($coolpay_state[0]) && $coolpay_state[0] == 'checkbox1') {
    $brandingId = $payment->getConfigData('brandingidchecked');
} else {
    $brandingId = $payment->getConfigData('brandingid');
}

$parameters = array(
    "agreement_id"                 => $payment->getConfigData("agreementid"),
    "amount"                       => $order->getTotalDue() * 100,
    "continueurl"                  => $this->getSuccessUrl(),
    "cancelurl"                    => $this->getCancelUrl(),
    "callbackurl"                  => $this->getCallbackUrl(),
    "language"                     => $payment->calcLanguage(Mage::app()->getLocale()->getLocaleCode()),
    "autocapture"                  => $payment->getConfigData('instantcapture'),
    "autofee"                      => $payment->getConfigData('transactionfee'),
    "payment_methods"              => $order->getPayment()->getMethodInstance()->getPaymentMethods(),
    "branding_id"                  => $brandingId,
    "google_analytics_tracking_id" => $payment->getConfigData('googleanalyticstracking'),
    "google_analytics_client_id"   => $payment->getConfigData('googleanalyticsclientid'),
    "customer_email"               => $order->getCustomerEmail() ?: '',
);

$result = Mage::helper('coolpaypayment')->qpCreatePayment($order);
$result = Mage::helper('coolpaypayment')->qpCreatePaymentLink($result->id, $parameters);

$paymentUrl = $result->url;
?>
    <script type="text/javascript">
        window.location.href = "<?php echo $paymentUrl; ?>";
    </script>
<?php exit(); ?>